"""Configuração inicial do banco de dados

Revision ID: c3a545577055
Revises: 
Create Date: 2018-01-23 18:11:19.302113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a545577055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pis', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('perfil_colaborador', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    op.create_index(op.f('ix_usuario_pis'), 'usuario', ['pis'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('integracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=240), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_hora_ultimo_registro', sa.DateTime(), nullable=True),
    sa.Column('id_colaborador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_colaborador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=240), nullable=True),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.Integer(), nullable=True),
    sa.Column('hora_fim', sa.Integer(), nullable=True),
    sa.Column('id_colaborador', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_colaborador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('justificativa', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=240), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('id_gestor', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_gestor'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['justificativa'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('justificativa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('ocorrencia')
    op.drop_table('integracao')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_pis'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
